# Generated by Django 4.2.17 on 2024-12-24 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='category',
            field=models.CharField(choices=[('GROCERIES', 'Groceries'), ('CLOTHING', 'Clothing'), ('ELECTRONICS', 'Electronics'), ('BOOKS', 'Books'), ('HOME_GARDEN', 'Home & Garden'), ('FASHION', 'Fashion'), ('SPORTS', 'Sports'), ('ENTERTAINMENT', 'Entertainment')], default='GROCERIES', max_length=20),
        ),
        migrations.AddField(
            model_name='coupon',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='coupons/'),
        ),
    ]
